[package]
name = "scim"
version = "0.16.21"
edition = "2024"

[dependencies]
scim-proto = { path = "../scim-proto" }
common = { path = "../common" }
jmap = { path = "../jmap" }
store = { path = "../store" }
registry = { path = "../registry" }
directory = { path = "../directory" }
http_proto = { path = "../http-proto" }
jmap_proto = { path = "../jmap-proto" }
types = { path = "../types" }
utils = { path = "../utils" }
trc = { path = "../trc" }
hyper = { version = "1.11.0", features = ["server", "http1", "http2"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hashify = { version = "0.2" }
xxhash-rust = { version = "0.8.18", features = ["xxh3"] }
percent-encoding = "2.3.2"
icu_locale = "2.3.1"

[dev-dependencies]

[features]
test_mode = []
dev_mode = []
enterprise = ["common/enterprise", "jmap/enterprise", "store/enterprise", "directory/enterprise", "trc/enterprise"]

[lints]
workspace = true
