[package]
name = "trc"
version = "0.16.16"
edition = "2024"

[dependencies]
event_macro = { path = "./event-macro" }
mail-auth = { version = "0.11", features = ["arc"] }
mail-parser = { version = "0.11", features = ["full_encoding"] }
base64 = "0.23.0"
serde = "1.0"
serde_json = "1.0.151"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "http2"]}
rtrb = "0.3.4"
parking_lot = "0.12.5"
tokio = { version = "1.53", features = ["net", "macros"] }
ahash = "0.8.12"
rkyv = { version = "0.8.17", features = ["little_endian"] }
compact_str = "0.10.0"
hashify = "0.2.9"

[features]
test_mode = []
dev_mode = []
enterprise = []

[dev-dependencies]
