/*
 * SPDX-FileCopyrightText: 2020 Stalwart Labs LLC <hello@stalw.art>
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-SEL
 */

use crate::{
    jmap::calendar::event::assert_eq_ignoring_updated,
    utils::{account::Account, jmap::JmapUtils, server::TestServer},
};
use groupware::cache::GroupwareCache;
use hyper::StatusCode;
use jmap_proto::request::method::MethodObject;
use serde_json::{Value, json};
use std::str::FromStr;
use types::{collection::SyncCollection, id::Id};

pub async fn test(test: &TestServer) {
    println!("Running Calendar Event instance tests...");
    let account = test.account("jdoe@example.com");

    let calendar_id = account
        .jmap_create(
            MethodObject::Calendar,
            [json!({
                "name": "Recurring events",
                "timeZone": "US/Eastern",
            })],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .created(0)
        .id()
        .to_string();

    let response = account
        .jmap_create(
            MethodObject::CalendarEvent,
            [
                json!({
                  "@type": "Event",
                  "uid": "recurring-instances@example.com",
                  "title": "Daily standup",
                  "start": "2007-03-05T12:00:00",
                  "duration": "PT1H",
                  "timeZone": "US/Eastern",
                  "updated": "2007-02-06T00:11:21Z",
                  "recurrenceRule": {
                    "frequency": "daily",
                    "count": 5
                  },
                  "locations": {
                    "loc1": {
                      "@type": "Location",
                      "name": "Room A"
                    }
                  },
                  "recurrenceOverrides": {
                    "2007-03-07T12:00:00": {
                      "title": "Moved standup",
                      "start": "2007-03-07T15:00:00",
                      "duration": "PT1H",
                      "updated": "2007-02-06T00:11:21Z"
                    }
                  },
                  "calendarIds": {
                    &calendar_id: true
                  }
                }),
                json!({
                  "@type": "Event",
                  "uid": "single-instance@example.com",
                  "title": "One off",
                  "start": "2007-03-12T09:00:00",
                  "duration": "PT2H",
                  "timeZone": "US/Eastern",
                  "updated": "2007-02-06T00:11:21Z",
                  "calendarIds": {
                    &calendar_id: true
                  }
                }),
            ],
            Vec::<(&str, &str)>::new(),
        )
        .await;
    let recurring_id = response.created(0).id().to_string();
    let single_id = response.created(1).id().to_string();
    test.wait_for_tasks().await;

    // The overridden occurrence keeps its original recurrence id
    let instances = expand_instances(account, &calendar_id).await;
    assert_eq!(
        starts(&instances),
        [
            "2007-03-05T12:00:00",
            "2007-03-06T12:00:00",
            "2007-03-07T15:00:00",
            "2007-03-08T12:00:00",
            "2007-03-09T12:00:00",
            "2007-03-12T09:00:00"
        ]
    );
    assert_eq!(
        instance(&instances, "2007-03-07T15:00:00").text_field("recurrenceId"),
        "2007-03-07T12:00:00"
    );

    // Unknown instances are reported as not found
    let unknown_id =
        Id::from_parts(1000, Id::from_str(&recurring_id).unwrap().document_id()).to_string();
    let response = account
        .jmap_update(
            MethodObject::CalendarEvent,
            [(&unknown_id, json!({"title": "Nope"}))],
            Vec::<(&str, &str)>::new(),
        )
        .await;
    assert_eq!(response.not_updated(&unknown_id).typ(), "notFound");

    // Updating an instance generated by the recurrence rule creates an override
    let id = instance_id(&instances, "2007-03-06T12:00:00");
    account
        .jmap_update(
            MethodObject::CalendarEvent,
            [(
                &id,
                json!({
                    "title": "Standup with guests",
                    "locations/loc1/name": "Room B"
                }),
            )],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .updated(&id);
    test.wait_for_tasks().await;

    let instances = expand_instances(account, &calendar_id).await;
    let updated = instance(&instances, "2007-03-06T12:00:00");
    assert_eq!(updated.text_field("title"), "Standup with guests");
    assert_eq!(updated.text_field("duration"), "PT1H");
    assert_eq!(
        updated
            .pointer("/locations/loc1/name")
            .and_then(|v| v.as_str()),
        Some("Room B")
    );
    assert_eq!(
        instance(&instances, "2007-03-05T12:00:00").text_field("title"),
        "Daily standup"
    );

    // Updating an occurrence that is already overridden patches the existing override
    let id = instance_id(&instances, "2007-03-07T15:00:00");
    account
        .jmap_update(
            MethodObject::CalendarEvent,
            [(
                &id,
                json!({
                    "title": "Moved standup, renamed"
                }),
            )],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .updated(&id);
    test.wait_for_tasks().await;

    assert_eq_ignoring_updated(
        &base_event(account, &recurring_id).await,
        json!({
            "id": &recurring_id,
            "title": "Daily standup",
            "locations": {
                "loc1": {
                    "@type": "Location",
                    "name": "Room A"
                }
            },
            "recurrenceOverrides": {
                "2007-03-06T12:00:00": {
                    "title": "Standup with guests",
                    "start": "2007-03-06T12:00:00",
                    "duration": "PT1H",
                    "locations": {
                        "loc1": {
                            "@type": "Location",
                            "name": "Room B"
                        }
                    }
                },
                "2007-03-07T12:00:00": {
                    "title": "Moved standup, renamed",
                    "start": "2007-03-07T15:00:00",
                    "duration": "PT1H"
                }
            }
        }),
    );

    // A rejected instance is not written, even when another instance of the same event is
    let instances = expand_instances(account, &calendar_id).await;
    let good_id = instance_id(&instances, "2007-03-09T12:00:00");
    let bad_id = instance_id(&instances, "2007-03-08T12:00:00");
    let response = account
        .jmap_update(
            MethodObject::CalendarEvent,
            [
                (&good_id, json!({"title": "Applied"})),
                (
                    &bad_id,
                    json!({"title": "Rejected", "utcStart": "2007-03-08T17:00:00Z"}),
                ),
            ],
            Vec::<(&str, &str)>::new(),
        )
        .await;
    response.updated(&good_id);
    assert_eq!(response.not_updated(&bad_id).typ(), "invalidProperties");
    test.wait_for_tasks().await;

    let base = base_event(account, &recurring_id).await;
    let mut overrides = base
        .pointer("/recurrenceOverrides")
        .and_then(|value| value.as_object())
        .unwrap()
        .keys()
        .map(String::as_str)
        .collect::<Vec<_>>();
    overrides.sort_unstable();
    assert_eq!(
        overrides,
        [
            "2007-03-06T12:00:00",
            "2007-03-07T12:00:00",
            "2007-03-09T12:00:00"
        ]
    );

    // Destroying an instance removes just that occurrence
    let instances = expand_instances(account, &calendar_id).await;
    let id = instance_id(&instances, "2007-03-08T12:00:00");
    assert_eq!(
        account
            .jmap_destroy(
                MethodObject::CalendarEvent,
                [&id],
                Vec::<(&str, &str)>::new(),
            )
            .await
            .destroyed()
            .collect::<Vec<_>>(),
        [id.as_str()]
    );
    test.wait_for_tasks().await;
    assert_eq!(
        starts(&expand_instances(account, &calendar_id).await),
        [
            "2007-03-05T12:00:00",
            "2007-03-06T12:00:00",
            "2007-03-07T15:00:00",
            "2007-03-09T12:00:00",
            "2007-03-12T09:00:00"
        ]
    );

    // Destroying an overridden instance does not bring back the original occurrence
    let instances = expand_instances(account, &calendar_id).await;
    let id = instance_id(&instances, "2007-03-07T15:00:00");
    assert_eq!(
        account
            .jmap_destroy(
                MethodObject::CalendarEvent,
                [&id],
                Vec::<(&str, &str)>::new(),
            )
            .await
            .destroyed()
            .collect::<Vec<_>>(),
        [id.as_str()]
    );
    test.wait_for_tasks().await;
    assert_eq!(
        starts(&expand_instances(account, &calendar_id).await),
        [
            "2007-03-05T12:00:00",
            "2007-03-06T12:00:00",
            "2007-03-09T12:00:00",
            "2007-03-12T09:00:00"
        ]
    );

    // Several instances of the same event may be changed in a single request
    let instances = expand_instances(account, &calendar_id).await;
    let update_id = instance_id(&instances, "2007-03-05T12:00:00");
    let destroy_id = instance_id(&instances, "2007-03-09T12:00:00");
    let response = account
        .jmap_method_calls(json!([[
            "CalendarEvent/set",
            {
                "accountId": account.id_string(),
                "update": {
                    &update_id: {
                        "title": "First standup"
                    }
                },
                "destroy": [&destroy_id]
            },
            "0"
        ]]))
        .await;
    response.updated(&update_id);
    assert_eq!(
        response.destroyed().collect::<Vec<_>>(),
        [destroy_id.as_str()]
    );
    test.wait_for_tasks().await;

    let instances = expand_instances(account, &calendar_id).await;
    assert_eq!(
        starts(&instances),
        [
            "2007-03-05T12:00:00",
            "2007-03-06T12:00:00",
            "2007-03-12T09:00:00"
        ]
    );
    assert_eq!(
        instance(&instances, "2007-03-05T12:00:00").text_field("title"),
        "First standup"
    );

    // Excluding the occurrence the event starts on is allowed
    let id = instance_id(&instances, "2007-03-05T12:00:00");
    assert_eq!(
        account
            .jmap_destroy(
                MethodObject::CalendarEvent,
                [&id],
                Vec::<(&str, &str)>::new(),
            )
            .await
            .destroyed()
            .collect::<Vec<_>>(),
        [id.as_str()]
    );
    test.wait_for_tasks().await;
    let instances = expand_instances(account, &calendar_id).await;
    assert_eq!(
        starts(&instances),
        ["2007-03-06T12:00:00", "2007-03-12T09:00:00"]
    );

    // A base event and its instances cannot be modified in the same request
    let id = instance_id(&instances, "2007-03-06T12:00:00");
    let response = account
        .jmap_update(
            MethodObject::CalendarEvent,
            [
                (&recurring_id, json!({"title": "Renamed"})),
                (&id, json!({"title": "Renamed instance"})),
            ],
            Vec::<(&str, &str)>::new(),
        )
        .await;
    for id in [&recurring_id, &id] {
        assert_eq!(response.not_updated(id).typ(), "invalidProperties");
        assert_eq!(
            response.not_updated(id).description(),
            "A base event and its instances cannot be modified in the same request."
        );
    }

    // Properties that are not per-occurrence are rejected
    for property in [
        json!({"calendarIds": {&calendar_id: true}}),
        json!({"isDraft": true}),
        json!({"utcStart": "2007-03-06T17:00:00Z"}),
        json!({"utcEnd": "2007-03-06T18:00:00Z"}),
        json!({"mayInviteSelf": true}),
        json!({"useDefaultAlerts": true}),
    ] {
        let response = account
            .jmap_update(
                MethodObject::CalendarEvent,
                [(&id, property)],
                Vec::<(&str, &str)>::new(),
            )
            .await;
        assert_eq!(response.not_updated(&id).typ(), "invalidProperties");
        assert_eq!(
            response.not_updated(&id).description(),
            "This property cannot be modified on a single occurrence."
        );
    }

    // Properties an occurrence inherits from the base event are ignored, not rejected
    account
        .jmap_update(
            MethodObject::CalendarEvent,
            [(
                &id,
                json!({
                    "@type": "Event",
                    "title": "Ignoring inherited properties",
                    "uid": "somebody-elses-uid@example.com",
                    "recurrenceRule": {"frequency": "weekly"},
                    "privacy": "private",
                    "participants/xyz/calendarAddress": "mailto:nobody@example.com"
                }),
            )],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .updated(&id);
    test.wait_for_tasks().await;

    let base = account
        .jmap_get(
            MethodObject::CalendarEvent,
            ["id", "uid", "recurrenceRule", "privacy", "participants"],
            [&recurring_id],
        )
        .await;
    let base = &base.list()[0];
    assert_eq!(base.text_field("uid"), "recurring-instances@example.com");
    assert_eq!(
        base.pointer("/recurrenceRule/frequency")
            .and_then(|v| v.as_str()),
        Some("daily")
    );
    assert_eq!(base.pointer("/privacy"), None);
    assert_eq!(base.pointer("/participants"), None);
    assert_eq!(
        instance(
            &expand_instances(account, &calendar_id).await,
            "2007-03-06T12:00:00"
        )
        .text_field("title"),
        "Ignoring inherited properties"
    );

    // Destroying an event that is also being updated through one of its instances fails
    let response = account
        .jmap_method_calls(json!([[
            "CalendarEvent/set",
            {
                "accountId": account.id_string(),
                "update": {
                    &id: {
                        "title": "Renamed instance"
                    }
                },
                "destroy": [&recurring_id]
            },
            "0"
        ]]))
        .await;
    assert_eq!(response.not_updated(&id).typ(), "willDestroy");
    assert_eq!(
        response.destroyed().collect::<Vec<_>>(),
        [recurring_id.as_str()]
    );
    test.wait_for_tasks().await;

    // A synthetic id of a non-recurring event refers to the event itself
    let instances = expand_instances(account, &calendar_id).await;
    let id = instance_id(&instances, "2007-03-12T09:00:00");
    assert_ne!(id, single_id);
    account
        .jmap_update(
            MethodObject::CalendarEvent,
            [(&id, json!({"title": "One off, renamed"}))],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .updated(&id);
    test.wait_for_tasks().await;

    assert_eq_ignoring_updated(
        &base_event(account, &single_id).await,
        json!({
            "id": &single_id,
            "title": "One off, renamed"
        }),
    );

    let instances = expand_instances(account, &calendar_id).await;
    let id = instance_id(&instances, "2007-03-12T09:00:00");
    assert_eq!(
        account
            .jmap_destroy(
                MethodObject::CalendarEvent,
                [&id],
                Vec::<(&str, &str)>::new(),
            )
            .await
            .destroyed()
            .collect::<Vec<_>>(),
        [id.as_str()]
    );
    test.wait_for_tasks().await;
    assert!(expand_instances(account, &calendar_id).await.is_empty());

    // Instances of floating all-day events keep their local time and duration
    let all_day_id = account
        .jmap_create(
            MethodObject::CalendarEvent,
            [json!({
              "@type": "Event",
              "uid": "all-day-instances@example.com",
              "title": "Spring break",
              "start": "2007-04-02T00:00:00",
              "duration": "P1D",
              "showWithoutTime": true,
              "updated": "2007-02-06T00:11:21Z",
              "recurrenceRule": {
                "frequency": "daily",
                "count": 3
              },
              "calendarIds": {
                &calendar_id: true
              }
            })],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .created(0)
        .id()
        .to_string();
    test.wait_for_tasks().await;

    let instances = expand_instances(account, &calendar_id).await;
    assert_eq!(
        starts(&instances),
        [
            "2007-04-02T00:00:00",
            "2007-04-03T00:00:00",
            "2007-04-04T00:00:00"
        ]
    );

    let update_id = instance_id(&instances, "2007-04-03T00:00:00");
    let destroy_id = instance_id(&instances, "2007-04-04T00:00:00");
    let response = account
        .jmap_method_calls(json!([[
            "CalendarEvent/set",
            {
                "accountId": account.id_string(),
                "update": {
                    &update_id: {
                        "title": "Spring break, day two"
                    }
                },
                "destroy": [&destroy_id]
            },
            "0"
        ]]))
        .await;
    response.updated(&update_id);
    assert_eq!(
        response.destroyed().collect::<Vec<_>>(),
        [destroy_id.as_str()]
    );
    test.wait_for_tasks().await;

    let instances = expand_instances(account, &calendar_id).await;
    assert_eq!(
        starts(&instances),
        ["2007-04-02T00:00:00", "2007-04-03T00:00:00"]
    );
    let updated = instance(&instances, "2007-04-03T00:00:00");
    assert_eq!(updated.text_field("title"), "Spring break, day two");
    assert_eq!(updated.text_field("duration"), "P1D");

    account
        .jmap_destroy(
            MethodObject::CalendarEvent,
            [&all_day_id],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .destroyed()
        .next()
        .unwrap();

    // Occurrences covered by a this-and-future change cannot be modified individually
    let dav_client = account.webdav_client();
    let account_id = account.id().document_id();
    let resources = test
        .server
        .fetch_dav_resources(account_id, account_id, SyncCollection::Calendar)
        .await
        .unwrap();
    let calendar_document_id = Id::from_str(&calendar_id).unwrap().document_id();
    let calendar_path = resources
        .paths
        .iter()
        .find(|path| {
            path.parent_id.is_none()
                && resources.resources[path.resource_idx].document_id == calendar_document_id
        })
        .map(|path| format!("{}{}", resources.base_path, path.path))
        .unwrap();

    dav_client
        .request(
            "PUT",
            &format!("{calendar_path}/this-and-future.ics"),
            THIS_AND_FUTURE_ICAL,
        )
        .await
        .with_status(StatusCode::CREATED);
    test.wait_for_tasks().await;

    let instances = expand_instances(account, &calendar_id).await;
    assert_eq!(
        starts(&instances),
        [
            "2007-03-05T12:00:00",
            "2007-03-06T12:00:00",
            "2007-03-07T14:00:00",
            "2007-03-08T14:00:00",
            "2007-03-09T14:00:00"
        ]
    );

    assert_eq!(
        instance(&instances, "2007-03-07T14:00:00").text_field("recurrenceId"),
        "2007-03-07T12:00:00"
    );
    for start in ["2007-03-08T14:00:00", "2007-03-09T14:00:00"] {
        assert_eq!(
            instance(&instances, start).text_field("recurrenceId"),
            start
        );
        let id = instance_id(&instances, start);
        let response = account
            .jmap_update(
                MethodObject::CalendarEvent,
                [(&id, json!({"title": "Should not apply"}))],
                Vec::<(&str, &str)>::new(),
            )
            .await;
        assert_eq!(response.not_updated(&id).typ(), "invalidProperties");
        assert_eq!(
            response.not_updated(&id).description(),
            "Occurrences of a this-and-future change cannot be modified individually."
        );

        let response = account
            .jmap_destroy(
                MethodObject::CalendarEvent,
                [&id],
                Vec::<(&str, &str)>::new(),
            )
            .await;
        assert_eq!(response.not_destroyed(&id).typ(), "invalidProperties");
    }

    // The occurrence the this-and-future change starts on is still editable
    let id = instance_id(&instances, "2007-03-07T14:00:00");
    account
        .jmap_update(
            MethodObject::CalendarEvent,
            [(&id, json!({"title": "Split renamed"}))],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .updated(&id);
    test.wait_for_tasks().await;

    let instances = expand_instances(account, &calendar_id).await;
    assert_eq!(
        starts(&instances),
        [
            "2007-03-05T12:00:00",
            "2007-03-06T12:00:00",
            "2007-03-07T14:00:00",
            "2007-03-08T14:00:00",
            "2007-03-09T14:00:00"
        ]
    );
    assert_eq!(
        instance(&instances, "2007-03-07T14:00:00").text_field("title"),
        "Split renamed"
    );

    dav_client
        .request(
            "DELETE",
            &format!("{calendar_path}/this-and-future.ics"),
            "",
        )
        .await
        .with_status(StatusCode::NO_CONTENT);

    // Patching an occurrence does not recompute its duration
    dav_client
        .request(
            "PUT",
            &format!("{calendar_path}/night-shift.ics"),
            NIGHT_SHIFT_ICAL,
        )
        .await
        .with_status(StatusCode::CREATED);
    test.wait_for_tasks().await;

    let instances = expand_instances(account, &calendar_id).await;
    assert_eq!(
        starts(&instances),
        ["2007-03-10T23:00:00", "2007-03-11T23:00:00"]
    );
    assert_eq!(
        instance(&instances, "2007-03-10T23:00:00").text_field("duration"),
        "PT5H"
    );

    let id = instance_id(&instances, "2007-03-10T23:00:00");
    account
        .jmap_update(
            MethodObject::CalendarEvent,
            [(&id, json!({"title": "Night shift, renamed"}))],
            Vec::<(&str, &str)>::new(),
        )
        .await
        .updated(&id);
    test.wait_for_tasks().await;

    let updated = expand_instances(account, &calendar_id).await;
    let updated = instance(&updated, "2007-03-10T23:00:00");
    assert_eq!(updated.text_field("title"), "Night shift, renamed");
    assert_eq!(updated.text_field("duration"), "PT5H");

    dav_client
        .request("DELETE", &format!("{calendar_path}/night-shift.ics"), "")
        .await
        .with_status(StatusCode::NO_CONTENT);

    // Clean up
    account
        .jmap_destroy(
            MethodObject::Calendar,
            [&calendar_id],
            [("onDestroyRemoveEvents", true)],
        )
        .await;
}

async fn expand_instances(account: &Account, calendar_id: &str) -> Vec<Value> {
    let ids = account
        .jmap_query(
            MethodObject::CalendarEvent,
            [
                ("inCalendar", Value::String(calendar_id.to_string())),
                ("after", Value::String("2007-03-01T00:00:00".to_string())),
                ("before", Value::String("2007-05-01T00:00:00".to_string())),
            ],
            ["start"],
            [
                ("timeZone", Value::String("US/Eastern".to_string())),
                ("expandRecurrences", Value::Bool(true)),
            ],
        )
        .await
        .ids()
        .map(|id| id.to_string())
        .collect::<Vec<_>>();
    if ids.is_empty() {
        return Vec::new();
    }

    account
        .jmap_get(
            MethodObject::CalendarEvent,
            [
                "id",
                "baseEventId",
                "start",
                "duration",
                "title",
                "recurrenceId",
                "locations",
            ],
            ids,
        )
        .await
        .list()
        .to_vec()
}

async fn base_event(account: &Account, id: &str) -> Value {
    account
        .jmap_get(
            MethodObject::CalendarEvent,
            ["id", "title", "locations", "recurrenceOverrides"],
            [id],
        )
        .await
        .list()[0]
        .clone()
}

fn starts(instances: &[Value]) -> Vec<&str> {
    instances
        .iter()
        .map(|instance| instance.text_field("start"))
        .collect()
}

fn instance<'x>(instances: &'x [Value], start: &str) -> &'x Value {
    instances
        .iter()
        .find(|instance| instance.text_field("start") == start)
        .unwrap_or_else(|| panic!("Missing instance starting at {start}: {instances:?}"))
}

fn instance_id(instances: &[Value], start: &str) -> String {
    instance(instances, start).id().to_string()
}

const THIS_AND_FUTURE_ICAL: &str = concat!(
    "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Test//EN\r\n",
    "BEGIN:VEVENT\r\nUID:this-and-future@example.com\r\nDTSTAMP:20070206T001121Z\r\n",
    "SUMMARY:Standup\r\nDTSTART;TZID=US/Eastern:20070305T120000\r\nDURATION:PT1H\r\n",
    "RRULE:FREQ=DAILY;COUNT=5\r\nEND:VEVENT\r\n",
    "BEGIN:VEVENT\r\nUID:this-and-future@example.com\r\nDTSTAMP:20070206T001121Z\r\n",
    "SUMMARY:Standup moved\r\n",
    "RECURRENCE-ID;TZID=US/Eastern;RANGE=THISANDFUTURE:20070307T120000\r\n",
    "DTSTART;TZID=US/Eastern:20070307T140000\r\nDURATION:PT1H\r\nEND:VEVENT\r\n",
    "END:VCALENDAR\r\n"
);

const NIGHT_SHIFT_ICAL: &str = concat!(
    "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Test//EN\r\n",
    "BEGIN:VEVENT\r\nUID:night-shift@example.com\r\nDTSTAMP:20070206T001121Z\r\n",
    "SUMMARY:Night shift\r\nDTSTART;TZID=US/Eastern:20070310T230000\r\n",
    "DTEND;TZID=US/Eastern:20070311T050000\r\nRRULE:FREQ=DAILY;COUNT=2\r\n",
    "END:VEVENT\r\nEND:VCALENDAR\r\n"
);
