[package]
name = "registry"
version = "0.16.21"
edition = "2024"

[dependencies]
utils = { path =  "../utils" }
trc = { path = "../trc" }
types = { path = "../types" }
serde = { version = "1.0", features = ["derive"]}
hashify = "0.2.9"
ahash = { version = "0.8" }
jmap-tools = { version = "0.1" }
mail-auth = { version = "0.12" }
tokio = { version = "1.53", features = ["fs"] }
lz4_flex = { version = "0.14", features = ["alloc"], default-features = false }

[features]
test_mode = []
enterprise = []

[lints]
workspace = true
